#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

app=$1
app_dir=$PLUSHU_APPS_DIR/$app

if [[ -f "$PLUSHU_DIR/APPS_DOMAIN" ]]; then
  apps_domain="$(<"$PLUSHU_DIR/APPS_DOMAIN")"
elif [[ -f "$PLUSHU_ROOT/APPS_DOMAIN" ]]; then
  apps_domain="$(<"$PLUSHU_ROOT/APPS_DOMAIN")"
fi

if [[ "$app" =~ ^([a-zA-Z0-9_\-]+\.?)+$ ]]; then
  printf '%s\n' "$app"
elif [[ -n "$apps_domain" && "$app" =~ ^[a-zA-Z0-9_\-]+$ ]]; then
  printf '%s\n' "$app.$apps_domain"
fi
