#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

app=$1
appslug="${app/\//-}"
app_dir=$PLUSHU_APPS_DIR/$app

if [[ "$appslug" == *.* ]]; then
  printf '%s\n' "$appslug"
elif [[ -f "$PLUSHU_ROOT/APPS_DOMAIN" ]]; then
  printf '%s\n' "$appslug.$(<"$PLUSHU_ROOT/APPS_DOMAIN")"
fi
