#!/usr/bin/env bash
set -eo pipefail; [[ $PLUSHU_TRACE ]] && set -x

app=$1
appslug="${app/\//-}"
app_dir=$PLUSHU_ROOT/apps/$app
domain_file=$app_dir/domains

if [[ "$appslug" == *.* ]]; then
  echo "$appslug"
elif [[ -f "$PLUSHU_ROOT/APPS_DOMAIN" ]]; then
  echo "$appslug.$(<"$PLUSHU_ROOT/APPS_DOMAIN")"
fi
